name: Auto Background Checking

on: 
  schedule:
    - cron: '30 8 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/HongKong"
    steps:
      # ============================================
      # TODO [√] 检查工作分支及 Workflows 运行环境
      # ============================================
      - name: Checkout
        uses: actions/checkout@v2
      # ============================================
      # TODO [√] 创建 Python3.6+ 编译环境
      # ============================================
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # ============================================
      # TODO [√] 安装 Project 第三方依赖
      # ============================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run checking
        run: |
          python main.py
        env:
          SENDER: ${{ secrets.SENDER }} 
          RECERVER: ${{ secrets.RECERVER }} 
          PASSWORD: ${{ secrets.PASSWORD }} 
